# Maven Build Pipeline
# This pipeline builds a Java project, runs tests, and can deploy Docker images.
# Learn more: https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: TestXMLs
    default: smoke.xml
    values:
      - studentTest.xml
      - smoke.xml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildTag: '$(Build.BuildId)'
  testSuiteName: 'test'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: clean package test -DsuiteXmlFile=xml-suites/${{ parameters.TestXMLs }}

- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnection'
    command: 'login'
    
- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnection'
    repository: 'anil/rest-assured-apis'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(buildTag)
      latest
